import { createHmac, timingSafeEqual } from 'crypto';
export const PRIVATE_ACCESS_COOKIE='havelent-private-access';
export const PRIVATE_ENTRY_COOKIE='havelent-private-entry';
export const configured=()=>Boolean(process.env.HAVELENT_VAULT_PASSWORD&&process.env.HAVELENT_VAULT_SESSION_SECRET);
const equal=(a:string,b:string)=>{const x=Buffer.from(a),y=Buffer.from(b);return x.length===y.length&&timingSafeEqual(x,y)};
export const passwordMatches=(v:string)=>(process.env.HAVELENT_VAULT_PASSWORD||'').split('|').some(password=>password.length>0&&equal(v,password));
export const accessToken=()=>createHmac('sha256',process.env.HAVELENT_VAULT_SESSION_SECRET||'').update('havelent-private-vault-v1').digest('hex');
export const validToken=(v?:string)=>Boolean(v&&configured()&&equal(v,accessToken()));
export const entryToken=()=>createHmac('sha256',process.env.HAVELENT_VAULT_SESSION_SECRET||'').update('havelent-private-entry-v1').digest('hex');
export const validEntryToken=(v?:string)=>Boolean(v&&configured()&&equal(v,entryToken()));
